### ISSUE TITLE
設定選択項目の追加

### ISSUE THREAD

**Issue by Yfuruchin** [MIERUNE/qgis-japan-mesh#16]
もし可能なら設定ウインドウでの「地理座標系」に「現在のキャンバスでの地理座標系」があるとありがたい
![image](https://github.com/MIERUNE/qgis-japan-mesh/assets/4961152/328b4c2f-8743-4027-8e50-9f5012efd2fc)

**Comment by ciscorn** [comment]
現在、出力先の座標参照系は、あえてこれらの地理座標系のみにしています（この選択肢は、JGD2011、2000, Tokyo などの、データムの情報を割り当てておけるようにするのが主な目的のつもりでした）。

というのも、経線・緯線が直交しない投影法の場合は、メッシュの各矩形に中間点を内挿して、非線形に曲がったポリゴンが吐かれるのが正しいですが、そこまでやる（あるいはそのような正しさまで責任を取る）のが難しいためです。

とはいえ、メッシュ生成時に中間点を内挿する機能を足す余地はありますね。

**Comment by ciscorn** [comment]
wontfix
